name: Run Discord Bot Daily

on:
  schedule:
    - cron: '21 21 * * *'  # every day at 21:30 UTC (23:30 GMT+2)
  workflow_dispatch:  # manual trigger too

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        API_KEY: ${{ secrets.API_KEY }}
      run: python main.py
